Funeral.Web/Areas/Admin/Models/ViewModel/PrintViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Funeral.Web.Areas.Admin.Models.ViewModel
{
    public class PrintViewModel
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public string PolicyNumber { get; set; }
        public string DatePaid { get; set; }
        public string AmountPaid { get; set; }
        public string PaidBy { get; set; }
        public string ReceivedBy { get; set; }
        public string MonthPaid { get; set; }
        public string ParlourName { get; set; }
        public string TimePrinted { get; set; }
        public string Underwriter { get; set; }
        public string BusinessAddressLine1 { get; set; }
        public string BusinessAddressLine2 { get; set; }
        public string BusinessAddressLine3 { get; set; }
        public string BusinessPostalCode { get; set; }
        public string FSBNumber { get; set; }
        public string telephoneNumber { get; set; }

        public string SurName { get; set; }
        public string FullName { get; set; }
        public string Barcode { get;set; }
    }
}

Funeral.Web/Areas/Admin/Controllers/ParlourController.cs
using System;
using System.Web.Mvc;

namespace Funeral.Web.Areas.Admin.Controllers
{
    public class ParlourController : BaseAdminController
    {
        // GET: Admin/Parlour
        [HttpPost]
        public void ChangeParlour(Guid parlourId)
        {
            if (!parlourId.Equals(Guid.Empty))
            {
                CurrentParlourId = parlourId;
            }
        }
    }
}

Funeral.Web/Areas/Admin/Controllers/PaymentsController.cs
using Funeral.BAL;
using Funeral.Model;
using Funeral.Web.App_Start;
using Funeral.Web.Areas.Admin.Models.ViewModel;
using Funeral.Web.Common;
using Microsoft.Reporting.WebForms;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Threading;
using System.Web.Mvc;
using System.Data;
using System.Linq;
using System.IO;
using System.Drawing;
using System.Drawing.Imaging;
using BarcodeLib;

namespace Funeral.Web.Areas.Admin.Controllers
{
    public class PaymentsController : BaseAdminController
    {
        private readonly ISiteSettings _siteConfig = new SiteSettings();
        public PaymentsController() : base(34)
        {
            this.dbPageId = 34;
        }
        public List<KeyValue> GetEntriesCount()
        {
            List<KeyValue> keyValues = new List<KeyValue>();
            keyValues.Add(new KeyValue { Key = "10", Value = "10" });
            keyValues.Add(new KeyValue { Key = "20", Value = "20" });
            keyValues.Add(new KeyValue { Key = "25", Value = "25" });
            keyValues.Add(new KeyValue { Key = "50", Value = "50" });
            keyValues.Add(new KeyValue { Key = "100", Value = "100" });
            keyValues.Add(new KeyValue { Key = "200", Value = "200" });
            keyValues.Add(new KeyValue { Key = "250", Value = "250" });
            keyValues.Add(new KeyValue { Key = "500", Value = "500" });
            return keyValues;
        }
        [PageRightsAttribute(CurrentPageId = 34, Right = new isPageRight[] { isPageRight.HasAccess })]
        public ActionResult Index()
        {
            //ViewBag.HasAccess = HasAccess;
            if (ViewBag.HasAccess == true)
            {
                var info = CultureInfo.InvariantCulture.Clone() as CultureInfo;
                info.NumberFormat.NumberDecimalSeparator = ".";

                CultureInfo cInfo = new CultureInfo(info.ToString());
                cInfo.NumberFormat.NumberDecimalSeparator = ".";

                Thread.CurrentThread.CurrentCulture = cInfo;

            }
            return View("Index");

        }

        [PageRightsAttribute(CurrentPageId = 34)]
        public PartialViewResult List()
        {
            var statusList = CommonBAL.GetStatus(FuneralEnum.StatusAssociatedTable.Members.ToString()).Select(x => new SelectListItem() { Text = x.ID.ToString(), Value = x.Status });
            ViewBag.StatusList = statusList;
            ViewBag.SocietyLists = CommonBAL.GetSocietyByParlourId(CurrentParlourId);
            ViewBag.HasEditRight = HasEditRight;
            ViewBag.HasDeleteRight = HasDeleteRight;
            Model.Search.PaymentSearchNew search = new Model.Search.PaymentSearchNew();
            search.StatusId = new Guid(CurrentParlourId.ToString());
            search.PageNum = 1;
            search.PageSize = 10;
            search.SarchText = string.Empty;
            search.SortBy = "";
            search.SortOrder = "Asc";
            search.TotalRecord = 0;
            var searchResult = new SearchResult<Model.Search.PaymentSearchNew, MembersPaymentModel>(search, new List<MembersPaymentModel>(), o => o.FullNames.Contains(search.SarchText));
            var pageCountEntries = GetEntriesCount();
            ViewBag.EntriesCount = pageCountEntries;
            var info = CultureInfo.InvariantCulture.Clone() as CultureInfo;
            info.NumberFormat.NumberDecimalSeparator = ".";

            ViewBag.CompanyDropDisplay = false;
            if (IsAdministrator)
            {
                ViewBag.CompanyDropDisplay = true;
                BindCompanyList("Search");
            }

            CultureInfo cInfo = new CultureInfo(info.ToString());
            cInfo.NumberFormat.NumberDecimalSeparator = ".";

            Thread.CurrentThread.CurrentCulture = cInfo;

            return PartialView("~/Areas/Admin/Views/Payments/_PaymentList.cshtml", search);
        }
        public ActionResult SearchData(Model.Search.PaymentSearchNew search)
        {
            var searchResult = new SearchResult<Model.Search.PaymentSearchNew, MembersPaymentModel>(search, new List<MembersPaymentModel>(), o => o.FullNames.Contains(search.SarchText) || o.IDNumber.Contains(search.SarchText) || o.MemeberNumber.Contains(search.SarchText) || o.PolicyStatus.Contains(search.SarchText));
            try
            {
                var otherPayment = MemberPaymentBAL.GetAllPayentMembers(search.StatusId, "", "", search.PageSize, search.PageNum, search.SortBy, search.SortOrder, "", search.BookName);
                return Json(new SearchResult<Model.Search.PaymentSearchNew, MembersPaymentModel>(search, otherPayment.MemberList, o => o.FullNames.Contains(search.SarchText) || o.IDNumber.Contains(search.SarchText) || o.MemeberNumber.Contains(search.SarchText) || o.PolicyStatus.Contains(search.SarchText)));
            }
            catch (Exception ex)
            {
                return Json(WebApiResult<Model.Search.PaymentSearchNew, MembersPaymentModel>.Error(searchResult, ex));
            }
        }
        [HttpGet]
        [PageRightsAttribute(CurrentPageId = 34)]
        public ActionResult ManageMembersPayment(int id, Guid ParlourID)
        {
            MembersPaymentDetailsModel model = MemberPaymentBAL.ReturnMemberPlanDetailsWithBalance(Convert.ToString(id), ParlourID);
            if (model != null)
            {
                model.Currency = Currency;
                if (model.PlanSubscription != null)
                {
                    ViewBag.totalPremium = model.PlanSubscription;
                }
                if (model.PaymentDate != null)
                {
                    ViewBag.Date = model.PaymentDate.ToString("dd-MMM-yyyy");
                }
                if (model.NextPaymentDate != null)
                {
                    ViewBag.PaymentDate = model.NextPaymentDate.ToString("MMM-yyyy");
                }
                if (model.PolicyStatus != null || model.PolicyStatus != "")
                {
                    ViewBag.PolicyStatus = model.PolicyStatus;
                }


                if (model.IsJoiningFee == false || model.IsJoiningFee.Equals(null))
                {
                    ViewBag.IsJoiningFee = false;
                }
                else if (model.IsJoiningFee == true)
                {
                    ViewBag.IsJoiningFee = true;
                }


                var policyBalance = model.Currency + " " + Convert.ToDouble(model.Balance);
                ViewBag.policyBalance = policyBalance;
                var latePanelty = model.Currency + " " + Convert.ToDouble(model.LatePaymentPenalty);
                ViewBag.LatePanelty = latePanelty;
                var totalPremium = model.Currency + " " + Convert.ToDouble(MembersBAL.SumOfPremium(id, ParlourID));
                ViewBag.TotalPremium = totalPremium;
                ViewBag.MemberInvoiceList = MembersBAL.GetInvoicesByMemberID(ParlourID, id);
                ViewBag.MemberID = model.MemeberNumber;
                ViewBag.ParlourID = ParlourID;
                var JoingingFee = model.JoiningFee;
                ViewBag.JoingingFee = JoingingFee;
            }
            var info = CultureInfo.InvariantCulture.Clone() as CultureInfo;
            info.NumberFormat.NumberDecimalSeparator = ".";

            CultureInfo cInfo = new CultureInfo(info.ToString());
            cInfo.NumberFormat.NumberDecimalSeparator = ".";

            Thread.CurrentThread.CurrentCulture = cInfo;
            return View(model);
        }
        [HttpPost]
        [PageRightsAttribute(CurrentPageId = 34, Right = new isPageRight[] { isPageRight.HasAdd })]
        public JsonResult AddPayments(MembersPaymentDetailsModel data)
        {
            //add Joining fee boolean in method
            MembersModel objmember = MembersBAL.GetMemberByID(data.pkiMemberID, ParlourId);
            if (objmember.MemberBranch != "")
            {
                data.Branch = objmember.MemberBranch;
            }
            data.ParlourId = ParlourId;
            data.NextPaymentDate = Convert.ToDateTime(data.PaymentDate).AddMonths(Convert.ToInt32(data.MonthOwing));
            var paymentId = MemberPaymentBAL.AddPayments(data, true);
            if (paymentId > 0)
            {
                TempData["message"] = ShowMessage(MessageType.Success, "Payment added successfully");
                return Json("Payment added successfully.", JsonRequestBehavior.AllowGet);
            }
            else
            {
                TempData["message"] = ShowMessage(MessageType.Danger, "Payment not added successfully");
                return Json("Payment not added successfully.", JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult JoiningFee(MembersPaymentDetailsModel data)
        {
            //add Joining fee boolean in method
            MembersModel objmember = MembersBAL.GetMemberByID(data.pkiMemberID, ParlourId);
            if (objmember.MemberBranch != "")
            {
                data.Branch = objmember.MemberBranch;
            }
            data.ParlourId = ParlourId;
            data.NextPaymentDate = Convert.ToDateTime(data.PaymentDate).AddMonths(Convert.ToInt32(data.MonthOwing));
            var paymentId = MemberPaymentBAL.AddPayments(data, true);
            return Json("JoiningFee added successfully.", JsonRequestBehavior.AllowGet);
        }
        public ActionResult PrintPaymentReceipt(int id, int Type, string PolicyNumber, string DatePaid, string AmountPaid, string PaidBy, string ReceivedBy, string MonthPaid, int memberId, Guid parlourId)
        {

            PrintViewModel printObj = new PrintViewModel();
            MembersModel memberModel = MembersBAL.GetMemberByID(memberId, parlourId);
            if (memberModel == null)
            {
                printObj.SurName = string.Empty;
                printObj.FullName = string.Empty;
            }
            else
            {

Funeral.Web/Areas/Admin/Views/GroupPayment/GroupPaymentView.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Scripts.Render("~/bundles/jquery")
<script src="~/Scripts/app/searchdatatable.js"></script>
<div class="row">
    <div id="GroupPaymentAddEdit"></div>
    <div id="GroupPaymentList"></div>
</div>
<script>
    var societyId = '@ViewBag.SocietyId';
    var hasRight = '@ViewBag.HasAccess';
	jQuery(function (jQuery) {
        jQuery(document).ready(function () {
                jQuery.noConflict();
                LoadSocietyList();
                LoadSocietyAddEdit();
                DOMIDs.AddEdit = "GroupPaymentAddEdit";
                DOMIDs.List = "GroupPaymentList";
        });
    });

	function LoadSocietyList() {
        jQuery.ajax({
            url: '@Url.Action("List", "GroupPayment", new {},Request.Url.Scheme)',
            type: "Get",
            contentType: "application/html; charset=utf-8",
            dataType: 'html'
        }).success(function (result) {jQuery("#" + DOMIDs.List).html(result);
        }).error(function (xhr, status) {alert(status);});
    }
    function LoadSocietyAddEdit() {
		var model = {};
            jQuery.ajax({
                url: '@Url.Action("Add", "GroupPayment", new {},Request.Url.Scheme)',
                type: "Post",
                data: JSON.stringify(model),
                contentType: "application/html; charset=utf-8",
                dataType: 'html'
            })
            .success(function (result) {
                jQuery("#" + DOMIDs.AddEdit).html(result);
            })
            .error(function (xhr, status) {
                alert(status);
            });
    }
</script>

Funeral.Web/Areas/Admin/Views/GroupPayment/Index.cshtml
@model Funeral.Model.MembersPaymentViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Scripts.Render("~/bundles/jquery")
<script src="~/Scripts/app/searchdatatable.js"></script>
<div class="row" id="MembersPaymentList"></div>
<script>
    var PkiMemberIDId = '@ViewBag.MemberID';
     var hasRight = '@ViewBag.HasAccess';
    jQuery(function ($) {
        jQuery(document).ready(function () {
            $.noConflict();
            LoadSocietyList();
                DOMIDs.List = "MembersPaymentList";
        });
    })

    function LoadSocietyList() {

        jQuery.ajax({
            url: '@Url.Action("GroupList", "GroupPayment", new {},Request.Url.Scheme)',
            type: "Get",
            contentType: "application/html; charset=utf-8",
            dataType: 'html'
        })
			.success(function (result) {
            jQuery("#" + DOMIDs.List).html(result);
        })
        .error(function (xhr, status) {
            alert(status);
        });
    }
</script>

Funeral.Web/Areas/Admin/Views/GroupPayment/_GroupPaymentList.cshtml
@model Funeral.Model.Search.BaseSearch
@Styles.Render("~/Content/datatablecss")
<script src="~/Scripts/plugins/dateformat/DateFormat.js"></script>
@using (Html.BeginForm())
{
	<div class="dataTables_wrapper" id="tblSocietySetupSearch_wrapper">
		<div class="col-lg-12">
			<div class="ibox ">
				<div class="ibox-title">
					<h5>Group Payment List</h5>
				</div>
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-lg-3" id="dvAdministrator">
                            <div class="form-group">
                                <label>Show entries</label>
                                @Html.DropDownListFor(m => m.PageSize, new SelectList(ViewBag.EntriesCount, "Value", "Key"), new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="col-sm-5 col-sm-offset-4">
                            <div class="form-group">
                                @Html.Label("Search Society:", new { @class = "control-label" })
                                <div class="input-group">
                                    @Html.TextBoxFor(m => m.SarchText, null, new { @class = "form-control", @maxlength = "50", placeholder = "Search by keyword" })
                                    <span class="input-group-btn">
                                        <input type="button" id="btnSearch" value="Search" class="btn btn-w-m btn-primary" />
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-9">
                            <asp:Label ID="lblRecords" runat="server" Text=""></asp:Label>
                        </div>
                    </div>
                    @{
                        var reversalModel = ViewBag.GroupInvoiceList;
                    }

                    <div class="row">
                        <div class="col-lg-12 ">
                            <div class="table-responsive">
                                @Html.EditorFor(model => model.PageNum, new { htmlAttributes = new { @class = "hidden", id = "PageNum1" } })
                                @Html.EditorFor(model => model.PageSize, new { htmlAttributes = new { @class = "hidden", id = "PageSize1" } })
                                @Html.Hidden("ItemId")
                                <table id="societySetupDataTable" class="table table-striped table-bordered table-hover" width="100%" cellspacing="0">
                                    <thead></thead>
                                    <tbody>
                                        <tr>
                                            <th class="hidden"></th>
                                            <th>Scheme Name</th>
                                            <th>Reference Number</th>
                                            <th>Amount</th>
                                            <th>Received By</th>
                                            @*<th>Payment Type</th>*@
                                            <th>Notes</th>
                                            <th>Date Paid</th>
                                            <th>Action</th>
                                        </tr>
                                        @if (reversalModel != null && reversalModel.Count > 0)
                                        {
                                            foreach (var item in reversalModel)
                                            {
                                        <tr>
                                            <td>@item.ApplicationName</td>
                                            <td>@item.ReferenceNumber</td>
                                            <td>@item.AmountPaid</td>
                                            <td>@item.RecievedBy</td>
                                            @*<td>@item.PaymentMethod</td>*@
                                            <td>@item.Notes</td>
                                            <td>@item.DatePaid</td>
                                            <td>
                                                @*<a href="@Url.Action("PrintForm", "GroupPayment", new { id = item.InvoiceID})">
        <i class="glyphicon glyphicon-print"></i>*@
                                                @*</a>&nbsp;&nbsp;<a href="@Url.Action("PrintPaymentReceipt", "Payments", new { id = item.InvoiceID, Type = 2, PolicyNumber = Model.MemeberNumber, DatePaid = item.DatePaid, AmountPaid = item.AmountPaid, PaidBy = item.PaidBy, ReceivedBy = item.RecievedBy, MonthPaid = item.Notes,MemberId=Model.pkiMemberID, parlourId=Model.ParlourId })">
        <i class="glyphicon glyphicon-export"></i>*@
                                                @*</a>*@

                                                @*<a href="@Url.Action("PrintForm", "GroupPayment", new{ GroupInvoiceID= item.GroupInvoiceID})"><i class="glyphicon glyphicon-print"></i></a>*@
                                                <div class="col-sm-4 text-center"><a href="@Url.Action("PrintForm", "GroupPayment", null, Request.Url.Scheme)?GroupInvoiceID=@item.GroupInvoiceID"><i class="glyphicon glyphicon-print"></i></a></div>

                                            </td>
                                            <td>

                                            @if (ViewBag.HasReversalPayment)
                                            {
                                                if (item.IsReversal == false && item.AmountPaid > 0)
                                                {
                                                    <a class="btn btn-w-m btn-primary grouppaymentreversal" role="@item.GroupInvoiceID" id="btnGroupReversalPayment" onclick="ReverseGroupPayment(@item.GroupInvoiceID)">Reversal Payment</a>
                                                }
                                            }
                                            </td>
                                        </tr>
                                            }
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
			</div>
		</div>
	</div>



	<script type="text/javascript">
        $(document).ready(function () {
            //ConfigureDatatable();
            InitDataTable();
            eventConfigs.pageChange.eventName = 'btnPageChanged';
            eventConfigs.pageChange.domElement = jQuery('#PageSize')[0];
            eventConfigs.searchClick.eventName = 'btnSearchClicked';
            eventConfigs.searchClick.domElement = jQuery('#btnSearch')[0];

            $('#PageSize').change(function () {
                InitModel();
                tableConfigs.table.DataTable().page.len(model1.PageSize).draw();
                eventConfigs.pageChange.dispatchEvent();
            });

            $("#btnSearch").click(function () {
                InitModel();
                tableConfigs.table.fnDraw();
                eventConfigs.searchClick.dispatchEvent();
            });
        });



        @*function ConfigureDatatable(){

            var sortOrder = @Html.Raw(Json.Encode(@Model.SortOrder));
            var sortBy =@Html.Raw(Json.Encode(@Model.SortBy));
            var totalRecord =@Html.Raw(Json.Encode(@Model.TotalRecord));
            var pageNum =@Html.Raw(Json.Encode(@Model.PageNum));
            var pageSize =@Html.Raw(Json.Encode(@Model.PageSize));
            var searchText =@Html.Raw(Json.Encode(@Model.SarchText));

			DOMIDs.Datatable = "societySetupDataTable";
            tableConfigs.SearchUrls = '@Url.Action("SearchData", "GroupPayment", new { }, Request.Url.Scheme)';
			setsearchmodel('200', sortOrder, sortBy, totalRecord, pageNum, pageSize, searchText);

            columnsArray =
				[{ "data": "GroupInvoiceID", "name": "GroupInvoiceID", "autoWidth": true, "visible": false },
                { "data": "ApplicationName", "name": "ApplicationName", "autoWidth": true },
                { "data": "ReferenceNumber", "name": "ReferenceNumber", "autoWidth": true },
                { "data": "AmountPaid", "name": "AmountPaid", "autoWidth": true },
                { "data": "RecievedBy", "name": "RecievedBy", "autoWidth": true },
                { "data": "PaymentMethod", "name": "PaymentMethod", "autoWidth": true },
				{
					"data": "DatePaid", "name": "DatePaid", "autoWidth": true,
					"render": function (data) {
						var date = new Date(parseInt(data.replace('/Date(', '')));
						return dateFormat(date, dateFormat.masks.isoDate, true);
					}
                },
                
				{
                    "render": function (data, type, full, meta) {*@


                    
                        @*var hasEditRights = '@ViewBag.HasEditRight' == "True" ? true : false;

                        var reverseModel = '@ViewBag.GroupInvoiceList';


                    
                            if (hasEditRights || hasDeleteRights) {

                                tableConfigs.table.DataTable().columns([4]).visible(true)
                                var dom = "<div class='row'>";

                                if (hasEditRights) {
                                    var editMemberUrl = '<div class="col-sm-4 text-center"><a  onclick="EditGroupPayment(\'' + full.GroupInvoiceID + '\')"><i class="fa fa-edit"></i></a></div>';
                                    dom = dom + editMemberUrl;
                                }

                                reverseModel.items.forEach(function (item) {
                                    if (item.isReversal == true)
                                        var reverseInvoiceUrl = '<div class="btn btn-w-m btn-primary  text-center" onclick="ReverseGroupPayment()"; >Reverse Payment</div>';
                                    dom = dom + reverseInvoiceUrl;
                                })
                                dom = dom + "</div>";
                                return dom;
                            }
                            else {
                                tableConfigs.table.DataTable().columns([5]).visible(false);
                                return "";
                            }*@
        //        }
        //    }];
        //}

        //function getReversalModel() {
        //    var reverseInvoiceUrl = '<div class="btn btn-w-m btn-primary  text-center" onclick="ReverseGroupPayment()"; >Reverse Payment</div>';
        //    dom = dom + reverseInvoiceUrl;

        //}

        function InitModel() {
            model1.PageNum = 1;
            model1.PageSize = jQuery('#PageSize').val();
            model1.SarchText = jQuery("#SarchText").val();
            jQuery("#PageNum1").val(model1.PageNum);
        }

        function EditGroupPayment(societyID) {
			jQuery("#ItemId").val(societyID);
            var editUrl = '@Url.Action("Edit", "GroupPayment", new { ID = "GroupInvoiceID" },Request.Url.Scheme)';
			editUrl = editUrl.replace("GroupInvoiceID", societyID);

            jQuery.ajax({
                url: editUrl,
                type: "Get",
                contentType: "application/html; charset=utf-8",
                dataType: 'html'
            })
            .success(function (result) {
				jQuery("#" + DOMIDs.AddEdit).html(result);
                window.scrollTo(0, 100);
                location.reload();
            })
            .error(function (xhr, status) {
                alert(status);
            });
            location.reload();
        }

        function ReverseGroupPayment(societyId) {

            var isConfirmed = confirm('You are about to reverse a Group Payment. Continue?');

            if (isConfirmed) {

				jQuery("#ItemId").val(societyId);
                var deleteUrl = '@Url.Action("GroupPaymentReversal","GroupPayment",new { ID = "GroupInvoiceID" },Request.Url.Scheme)';
				deleteUrl = deleteUrl.replace("GroupInvoiceID", societyId);

                model1.PageNum = 1;

                jQuery.ajax({
                    url: deleteUrl,
                    type: "Get",
                    contentType: "application/html; charset=utf-8",
                    dataType: 'html'
                })
                .success(function (result) {
                    InitModel();
                    tableConfigs.table.fnDraw();
                    location.reload();
                })
                .error(function (xhr, status) {
                    alert(status);
                });
            }
        }



        //+++++++++++++++++++++++++++++Test+++++++++++++++++++++++

        function ReverseGroupPayment(societyId) {

            var isConfirmed = confirm('Are you sure you want to Reverse?');

            if (isConfirmed) {

				jQuery("#ItemId").val(societyId);
                var ReverseUrl = '@Url.Action("GroupPaymentReversal", "GroupPayment",new { ID = "GroupInvoiceID" },Request.Url.Scheme)';
                ReverseUrl = ReverseUrl.replace("GroupInvoiceID", societyId);

                model1.PageNum = 1;

                jQuery.ajax({
                    url: ReverseUrl,
                    type: "Get",
                    contentType: "application/html; charset=utf-8",
                    dataType: 'html'
                })
                .success(function (result) {
                    InitModel();
                    tableConfigs.table.fnDraw();
                })
                .error(function (xhr, status) {
                    alert(status);
                });
            }
        }
	</script>
}