Funeral.Web/Areas/Admin/Controllers/ClaimsController.cs
using Funeral.BAL;
using Funeral.Model;
using Funeral.Model.Search;
using Funeral.Web.Areas.Admin.Models;
using Funeral.Web.Common;
using Microsoft.Reporting.WebForms;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using static Funeral.Model.FuneralEnum;
using Funeral.Web.App_Start;
using Funeral.Web.Areas.Admin.Models.ViewModel;
using System.Data;
using System.Data.SqlClient;
using System.Globalization;
using System.Web.UI.WebControls;
using DocumentFormat.OpenXml.Office2013.PowerPoint.Roaming;


namespace Funeral.Web.Areas.Admin.Controllers
{
    public class ClaimsController : BaseAdminController
    {
        private readonly ISiteSettings _siteConfig = new SiteSettings();

        // GET: Admin/Claims
        #region Claim Main View
        public ActionResult Index(string Status)
        {
            ClaimSearch search = new ClaimSearch();
            search.CompanyId = new Guid(CurrentParlourId.ToString());
            search.PageNum = 1;
            search.PageSize = 10;
            search.SarchText = "";
            search.SortBy = "";
            search.SocietyID = "";
            search.SortOrder = "Asc";
            search.StatusId = Status == null ? "0" : Status;
            search.TotalRecord = 0;
            search.DateFrom = new DateTime(2019, 01, 01);
            search.DateTo = DateTime.Now;

            List<StatusModel> statusList = new List<StatusModel>();
            var StatusId = Request.Params["StatusId"];
            if (StatusId == null)
            {
                statusList = Status == null ? ClaimsBAL.GetClaimsStatus() : ClaimsBAL.GetClaimsStatus().Where(x => x.Status == Status).ToList();
                search.SearchType = "Normal";
            }
            else
            {
                search.SearchType = StatusId;
                if (!ClaimStatusTypes.Where(x => x.Key.Equals(StatusId)).FirstOrDefault().Value.ToString().Equals("All"))
                {
                    var GetStatusId = ClaimStatusTypes.Where(x => x.Key.Equals(StatusId)).FirstOrDefault().Value.ToString().Split(',').ToList();
                    HashSet<int> StatusIdCollection = new HashSet<int>(GetStatusId.Select(s => Convert.ToInt32(s)));
                    statusList = ClaimsBAL.GetClaimsStatus().Where(m => StatusIdCollection.Contains(m.ID)).ToList();
                }
                else
                    statusList = ClaimsBAL.GetClaimsStatus();
            }
            ViewBag.SocietyLists = CommonBAL.GetSocietyByParlourId(CurrentParlourId);
            ViewBag.Statuses = statusList;
            LoadEntriesCount();
            BindCompanyList("Search");
            var bankList = CommonBAL.GetBankList();
            ViewBag.Banks = bankList;
            ViewBag.Provinces = CommonBAL.GetProvinces();
            var AccountList = CommonBAL.GetAccountTypeList();
            ViewBag.Accounts = AccountList;
            var searchResult = new Funeral.Model.SearchResult<Model.Search.ClaimSearch, ClaimsModel>(search, new List<ClaimsModel>(),
                o => o.ClaimNotes.Contains(search.SarchText)
                || o.MemberNumber.Contains(search.SarchText)
                || o.CourseOfDearth.Contains(search.SarchText)
                || o.ClaimantTitle.Contains(search.SarchText)
                || o.ClaimantFullname.Contains(search.SarchText)
                || o.ClaimantSurname.Contains(search.SarchText)
                || o.ClaimantIDNumber.Contains(search.SarchText)
                || o.ClaimantAddressLine1.Contains(search.SarchText)
                || o.ClaimantAddressLine2.Contains(search.SarchText)
                || o.ClaimantAddressLine3.Contains(search.SarchText)
                || o.ClaimantAddressLine4.Contains(search.SarchText)
                || o.ClaimantCode.Contains(search.SarchText)
                || o.ClaimantContactNumber.Contains(search.SarchText));
            return View(search);
        }
        #endregion
        #region LoadEntriesCount
        public void LoadEntriesCount()
        {
            List<KeyValue> keyValues = new List<KeyValue>();
            List<SelectListItem> entriesItems = new List<SelectListItem>();
            keyValues.Add(new KeyValue { Key = "10", Value = "10" });
            keyValues.Add(new KeyValue { Key = "20", Value = "20" });
            keyValues.Add(new KeyValue { Key = "25", Value = "25" });
            keyValues.Add(new KeyValue { Key = "50", Value = "50" });
            keyValues.Add(new KeyValue { Key = "100", Value = "100" });
            keyValues.Add(new KeyValue { Key = "200", Value = "200" });
            keyValues.Add(new KeyValue { Key = "250", Value = "250" });
            keyValues.Add(new KeyValue { Key = "500", Value = "500" });
            ViewBag.EntriesCount = keyValues;
        }
        #endregion
        #region SearchData
        [HttpPost]
        public ActionResult SearchData(ClaimSearch search)
        {
            DateTime Datefrom = Convert.ToDateTime("01/01/1753");
            var dateAndTime = DateTime.Now;
            DateTime DateTo = dateAndTime.Date;
            if (search.DateFrom != null || search.DateTo != null)
            {
                Datefrom = search.DateFrom;
                dateAndTime = search.DateTo;

            }

            var getExpectedClaimStatus = ClaimsBAL.GetExpectedClaimStatusList(UserID);
            HashSet<string> expectedStatus = new HashSet<string>(getExpectedClaimStatus.Select(s => s.Status));
            var searchResult = new Funeral.Model.SearchResult<Model.Search.ClaimSearch, ClaimsModel>(search, new List<ClaimsModel>(),
               o => (o.ClaimNotes.Contains(search.SarchText)
               || o.Status.ToLower().Contains(search.StatusId.ToLower())
               || o.MemberNumber.Contains(search.SarchText)
               || o.CourseOfDearth.Contains(search.SarchText)
               || o.ClaimantTitle.Contains(search.SarchText)
               || o.ClaimantFullname.Contains(search.SarchText)
               || o.ClaimantSurname.Contains(search.SarchText)
               || o.ClaimantIDNumber.Contains(search.SarchText)
               || o.ClaimantAddressLine1.Contains(search.SarchText)
               || o.ClaimantAddressLine2.Contains(search.SarchText)
               || o.ClaimantAddressLine3.Contains(search.SarchText)
               || o.ClaimantAddressLine4.Contains(search.SarchText)
               || o.ClaimantCode.Contains(search.SarchText)
               || expectedStatus.Contains(o.Status)
               || o.ClaimantContactNumber.Contains(search.SarchText)) && (o.CreatedDate >= Datefrom && o.CreatedDate <= dateAndTime));
            try
            {
                List<ClaimsModel> members = new List<ClaimsModel>();
                members = ClaimsBAL.SelectAllClaims(search.CompanyId).Where(x => x.Status.Contains(search.StatusId == "0" ? "" : search.StatusId)).ToList();
                if (!string.IsNullOrEmpty(search.SocietyID) && search.SocietyID != "0")
                    members = members.Where(x => x.SocietyID.ToString() == search.SocietyID).ToList();
                //members = IsAdministrator == true || IsSuperUser == true ? members : members = members.Where(m => (expectedStatus.Contains(m.Status))).ToList();
                //members = IsAdministrator == true || HasAccess == true ? members : members = members.Where(m => (expectedStatus.Contains(m.Status))).ToList();

                if (search.SearchType != null && search.SearchType != "Normal")
                {
                    if (!ClaimStatusTypes.Where(x => x.Key.Equals(search.SearchType)).FirstOrDefault().Value.ToString().Equals("All"))
                    {
                        var GetStatusId = ClaimStatusTypes.Where(x => x.Key.Equals(search.SearchType)).FirstOrDefault().Value.ToString().Split(',').ToList();
                        HashSet<int> StatusIdCollection = new HashSet<int>(GetStatusId.Select(s => Convert.ToInt32(s)));
                        var statusList = ClaimsBAL.GetClaimsStatus().Where(m => StatusIdCollection.Contains(m.ID)).Select(x => x.Status).ToList();
                        members = members.Where(m => statusList.Contains(m.Status)).ToList();
                    }
                    else
                    {
                        members = members.Where(m => m.AssignedTo == 0).ToList();
                    }
                }

                var searchDatatable = new Funeral.Model.SearchResult<Model.Search.ClaimSearch, ClaimsModel>(search, members, o => (o.ClaimNotes.Contains(search.SarchText.ToLower())
                    || o.ClaimNotes.ToLower().Contains(search.SarchText.ToLower())
                    || o.CourseOfDearth.ToLower().Contains(search.SarchText.ToLower())
                    || o.ClaimantTitle.ToLower().Contains(search.SarchText.ToLower())
                    || o.ClaimantFullname.ToLower().Contains(search.SarchText.ToLower())
                    || o.ClaimantSurname.ToLower().Contains(search.SarchText.ToLower())
                    || o.ClaimantIDNumber.ToLower().Contains(search.SarchText.ToLower())
                    || o.ClaimantAddressLine1.ToLower().Contains(search.SarchText.ToLower())
                    || o.ClaimantAddressLine2.ToLower().Contains(search.SarchText.ToLower())
                    || o.ClaimantAddressLine3.ToLower().Contains(search.SarchText.ToLower())
                    || o.ClaimantAddressLine4.ToLower().Contains(search.SarchText.ToLower())
                    || o.ClaimantCode.ToLower().Contains(search.SarchText.ToLower())
                    || o.ClaimantContactNumber.ToLower().Contains(search.SarchText.ToLower())) && (o.CreatedDate >= Datefrom && o.CreatedDate <= dateAndTime));
                return Json(searchDatatable, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {

Funeral.Web/Areas/Admin/Views/Claims/ClaimDashboard.cshtml
@model Funeral.Model.Dashboard
@{
    ViewBag.Title = "Claim Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript">
    $(function () {
        RenderClaimDashboard(document.getElementById("CompanyList"))
    });
    function RedirectToClaimPage(CurrentValue) {
        $.post("@Url.Action("Index","Claims")", { Status: CurrentValue }, function (result) {});
    }
    function RenderClaimDashboard(Control) {
        var CompanyId = Control.value;
        if (CompanyId != null && CompanyId != "") {
            BindGroupDropdown(CompanyId);
            var BookId = $("#ddlClaimSociety").val();
            LoadClaimDashboard(CompanyId,BookId)
        }
        else {
            alert("Please select Scheme");
        }
    }
    function LoadClaimDashboard(CompanyId, BookId) {
        var Geturl = "@Url.Action("RenderClaimDashboard", "Claims", new {CompanyId="GetCompanyId",BookId="getBookId"})".replace("GetCompanyId", CompanyId).replace("amp;", "").replace("getBookId", BookId);
        $.ajax({
            url: Geturl,
            type: 'GET',
            cache: false,
        }).done(function (result) { $('#dvClaimDashboardRendering').empty().html(result); });
    }
    function BindGroupDropdown(ParlourId) {
        var ddlCustomers = $("#ddlClaimSociety");
        ddlCustomers.empty().append('<option selected="selected" value="0">All</option>');
        jQuery.ajax({
            url: '@Url.Action("BindGroupByCompanyId","Claims")',
            data: { CompanyId: ParlourId },
            type: "post",
            success: function (response) {
                ddlCustomers.empty().append('<option selected="selected" value="0">All</option>');
                jQuery.each(response, function () {
                    ddlCustomers.append($("<option></option>").val(this['Value']).html(this['Text']));
                });
            },
            failure: function (response) {
                alert(response.responseText);
            },
            error: function (response) {
                alert(response.responseText);
            }
        });
    }
     function ChangeBook_LoadDashboard(Control) {
        var BookId = Control.value;
        if (BookId != null && BookId != "") {
            var CompanyId = $("#CompanyList").val();
            LoadClaimDashboard(CompanyId,BookId)
        }
        else {
            alert("Please select Book");
        }
    }


</script>
<div class="row">
    <div class="col-lg-12">
        <div class="ibox ">
            <div class="ibox-title">
                <h5>Claim Dashboard</h5>
            </div>
            <div class="ibox-content">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Scheme: </label>
                            @Html.DropDownList("CompanyList", new SelectList(ViewBag.Companies, "parlourid", "ApplicationName"), new { @onchange = "RenderClaimDashboard(this)", @class = "form-control" })
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Book: </label>
                            <select class="form-control" id="ddlClaimSociety" onchange="ChangeBook_LoadDashboard(this)"></select>
                        </div>
                    </div>
                </div>
                <div id="dvClaimDashboardRendering"></div>
            </div>
        </div>
    </div>
</div>


<script src="~/Scripts/app/searchdatatable.js"></script>
<script src="~/Scripts/plugins/ChartJScript/ChartJS_script.js"></script>
<script type="text/javascript">
     var IsDisplayDashboarTable = @Html.Raw(Json.Encode(Model.IsDisplayDashboarTable));
    if (IsDisplayDashboarTable == true)
    {
      function LoadFuneralList() {
        jQuery.ajax({
            url: '@Url.Action("List", "Dashboard", new {},Request.Url.Scheme)',
            type: "Get",
            contentType: "application/html; charset=utf-8",
            dataType: 'html'
        })
            .success(function (result) {
                    jQuery("#DashboardList").html(result);
        })
        .error(function (xhr, status) {
            alert(status);
        });
        }
        $(document).ready(function () {
            LoadFuneralList();
        });
    }
</script>
<div class="row">
    <div class="col-lg-12">
        <div class="ibox ">
            @*<div class="ibox-content" id="DivpaymentCollection">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="widget style1 red-bg">
                            <div class="row">
                                <div class="col-sm-4 text-left">
                                    <i class="fa fa-envelope-o fa-5x"></i>
                                </div>
                                <div class="col-sm-8 text-right">
                                    <span>SMS Credits</span>
                                    <h2 class="font-bold" id="OpenModel">
                                        <label id="lblTotalSMSCreditsCount" data-toggle="modal" data-target="#divSMSTopupModal">@Model.TotalSMSCreditsCount</label>
                                    </h2>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="widget style1 red-bg">
                            <div class="row">
                                <div class="col-sm-4 text-left">
                                    <i class="fa fa-bell fa-5x"></i>
                                </div>
                                <div class="col-sm-8 text-right">
                                    <span>Outstanding Payments</span>
                                    <h2 class="font-bold">
                                        <label id="lblOutstandingPaymentsCount" data-toggle="modal" data-target="#divOutstandingSendMessages">@Model.OutstandingPaymentsCount</label>
                                    </h2>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="widget style1 red-bg">
                            <div class="row">
                                <div class="col-sm-4 text-left">
                                    <i class="fa fa-trophy fa-5x"></i>
                                </div>
                                <div class="col-sm-8 text-right">
                                    <span>Premium Collected</span>
                                    <h2 class="font-bold">
                                        <label id="lblTodayTotalPayment" data-toggle="modal" data-target="#divGenerateCashUpReport_FromDashboard">@Model.TodayTotalPayment</label>
                                    </h2>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>*@
            <div class="ibox-content">
                @{ Html.RenderPartial("~/Areas/Admin/Views/Claims/ClaimDashboardChart.cshtml", Model.dashboardChart); }
            </div>

            @*<div class="ibox-content">
                <div class="row" id="DashboardList"></div>
            </div>*@

        </div>
    </div>
</div>



@*<div class="ibox-content">
        @{ Html.RenderPartial("~/Areas/Admin/Views/Claims/ClaimDashboardChart.cshtml", Model.ClaimDashboardChart); }
    </div>

    <div class="ibox-content">
        <div class="row" id="DashboardList"></div>
    </div>*@

Funeral.Web/Areas/Admin/Views/Claims/_ChangeAssignedForm.cshtml
@model Funeral.Model.ClaimAssigned

<div class="modal fade" id="dvChangeStatusModel" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;  </button>
                <h4 class="modal-title">Change Claim Assigned</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    @{
                        using (Html.BeginForm("ChangeClaimAssigned", "Claims", FormMethod.Post))
                        {
                            @Html.HiddenFor(x => x.ClaimId)
                            @Html.HiddenFor(x => x.CurrentAssigned)
                            @Html.HiddenFor(x => x.ParlourId)
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <div class="col-sm-12">
                                        <label>Select User * </label>
                                        @Html.DropDownListFor(x => x.NewAssigned, new SelectList(ViewBag.AllUserList, "PkiUserID", "EmployeeFullname"), "Select User", new { @class = "form-control", @required = true })
                                        @Html.ValidationMessageFor(x => x.NewAssigned, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-12">
                                        <br />
                                        <input type="submit" value="Submit" class="btn btn-sm btn-primary pull-right" />
                                    </div>
                                </div>
                            </div>
                        }
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Funeral.Web/Areas/Admin/Views/Claims/_ClaimDashboard.cshtml
@model Funeral.Model.ClaimDashbo
    ard
@{
    string CostCount = null;
    string CostAmount = null;

    string CostCount1 = null;
    string CostAmount1 = null;

    if (Model.claimCostGraphs != null)
    {
        string CostClaimCount = "['# of Claims',";
        string CostClaimAmount = "['Cost',";

        string Flow_CostCount1 = "[";
        string Flow_CostAmount1 = "[";
        foreach (var item in Model.claimCostGraphs)
        {
            CostClaimCount += item.ClaimCount + ",";
            CostClaimAmount += item.ClaimAmount + ",";

            string j = item.UnixCreatedDate.ToString() + "000";

            Flow_CostCount1 += "[" + Convert.ToInt64(j) + "," + item.ClaimCount + "],";
            Flow_CostAmount1 += "[" + Convert.ToInt64(j) + "," + item.ClaimAmount + "],";

        }
        CostCount = CostClaimCount.TrimEnd(',') + "]";
        CostAmount = CostClaimAmount.TrimEnd(',') + "]";

        CostCount1 = Flow_CostCount1.TrimEnd(',') + "]";
        CostAmount1 = Flow_CostAmount1.TrimEnd(',') + "]";
    }
    string PolicyCost = null;
    string PolicyName = null;
    string PolicyAmount = null;
    string ColorArray = null;
    if (Model.claimPolicyGraph != null)
    {
        foreach (var item in Model.claimPolicyGraph)
        {
            PolicyCost += item.ClaimCount + ",";
            PolicyAmount += item.ClaimAmount + ",";
            PolicyName += "'" + item.ApplicationName + "',";
            ColorArray += "'" + String.Format("#{0:X6}", new Random((int)DateTime.Now.Ticks).Next(0x1000000)) + "',";
        }
        PolicyCost = "[" + PolicyCost.TrimEnd(',') + "]";
        PolicyAmount = "[" + PolicyAmount.TrimEnd(',') + "]";
        PolicyName = "[" + PolicyName.TrimEnd(',') + "]";
        ColorArray = "[" + ColorArray.TrimEnd(',') + "]";
    }
}
<script type="text/javascript">
    $(function () {
        var oilprices = @Html.Raw(CostCount1);
        var exchangerates =@Html.Raw(CostAmount1);
        function euroFormatter(v, axis) {
            return v.toFixed(axis.tickDecimals) + "R";
        }

        function LoadClaimCostChart(position) {
            $.plot($("#ClaimCost_chartmultiline"), [{
                data: oilprices,
                label: "# of Claims"
            }, {
                data: exchangerates,
                label: "Cost",
                yaxis: 2
            }], {
                    xaxes: [{ mode: 'time' }],
                    yaxes: [{ min: 0 }, {
                        // align if we are to the right
                        alignTicksWithAxis: position == "right" ? 1 : null,
                        position: position,
                        tickFormatter: euroFormatter
                    }],
                    legend: {
                        position: 'sw'
                    },
                    colors: ["#0000FF", "#FF4500"],
                    grid: {
                        color: "#999999",
                        hoverable: true,
                        clickable: true,
                        tickColor: "#D4D4D4",
                        borderWidth: 0,
                        hoverable: true //IMPORTANT! this is needed for tooltip to work,
                    },
                    tooltip: true,
                    tooltipOpts: {
                        content: "%y %s for %x",
                        xDateFormat: "%d-%m-%Y",
                        onHover: function (flotItem, $tooltipEl) { }
                    }
                });
        }
        LoadClaimCostChart("right");
        $("button").click(function () {
            LoadClaimCostChart($(this).text());
        });
        LoadApexChart_ClaimDashboard("ClaimCount_apexChart", @Html.Raw(PolicyCost), @Html.Raw(PolicyName),"Policy Wise Claim Count","Count");
        LoadApexChart_ClaimDashboard("ClaimCost_apexChart",@Html.Raw(PolicyAmount),@Html.Raw(PolicyName),"Policy Wise Claim Cost","R");
    });
    function LoadApexChart_ClaimDashboard(ChartId, Claimdata, PolicyName,titeltext,TooltipText) {
        var options = {
            series: [{ data: Claimdata }],
            chart: {
                type: 'bar', height: 350,
                toolbar: { show: false, },
            },
            plotOptions: { bar: { horizontal: true, } },
            dataLabels: { enabled: false },
            xaxis: { categories: PolicyName, },
            title: {
                text: titeltext,
                align: 'center',
                floating: true
            },
            tooltip: {
                theme: 'dark',
                y: {
                    title: {
                        formatter: function () {
                            return TooltipText + ' '
                        }
                    }
                }
            }
        };
        var chart = new ApexCharts(document.querySelector("#" + ChartId), options);
        chart.render();
    }
    $(document).ready(function () {
        c3.generate({
            bindto: '#lineChart',
            data: {
                columns: [
                    @Html.Raw(CostCount),//['# of Claims', 30, 200, 100, 400, 150, 250],
                    @Html.Raw(CostAmount)//['Cost', 50, 20, 10, 40, 15, 25]
                ],
                colors: {
                    data1: '#1ab394',
                    data2: '#BABABA'
                }
            }
        });
    })

</script>
<div class="row">
    <div class="col-lg-4">
        <div class="widget style1 red-bg">
            <div class="row">
                <div class="col-sm-4 text-left">
                    <i class="fa fa-check-square-o fa-5x"></i>
                </div>
                <div class="col-sm-8 text-right">
                    <span>Claim Count</span>
                    <h2 class="font-bold" id="OpenModel">
                        @if (Model.claimDashboardLabel != null)
                        {
                            <label> @Model.claimDashboardLabel.ClaimsCount</label>
                        }
                        else
                        {
                            <label>0</label>
                        }
                    </h2>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="widget style1 red-bg">
            <div class="row">
                <div class="col-sm-4 text-left">
                    <i class="fa fa-bell fa-5x"></i>
                </div>
                <div class="col-sm-8 text-right">
                    <span>Payout Amount</span>
                    <h2 class="font-bold">
                        @if (Model.claimDashboardLabel != null)
                        {
                            <label>R @Model.claimDashboardLabel.PayoutAmount.ToString("0.00")</label>
                        }
                        else
                        {
                            <label>R 0.00</label>
                        }

                    </h2>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="widget style1 red-bg">
            <div class="row">
                <div class="col-sm-4 text-left">
                    <i class="fa fa-trophy fa-5x"></i>
                </div>
                <div class="col-sm-8 text-right">
                    <span>Claim Amount</span>
                    <h2 class="font-bold">
                        @if (Model.claimDashboardLabel != null)
                        {
                            <label>R @Model.claimDashboardLabel.CoverAmount.ToString("0.00")</label>
                        }
                        else
                        {
                            <label>R 0.00</label>
                        }
                    </h2>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="table-responsive">
            <table id="ClaimStatusDataTable" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Status</th>
                        <th>Count</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        if (Model.claimStatuses != null ? (Model.claimStatuses.Count > 0 ? true : false) : false)
                        {
                            for (int i = 0; i < Model.claimStatuses.Count; i++)
                            {
                                <tr>
                                    <td><b>@Model.claimStatuses[i].Status</b></td>
                                    <td><b><a href="@Url.Action("Index","Claims",new {Status= Model.claimStatuses[i].Status})">@Model.claimStatuses[i].StatusCount</a></b></td>
                                </tr>
                            }
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="ibox ">
            <div class="ibox-title">
                <h5>
                    Claim Cost
                </h5>
            </div>
            <div class="ibox-content">
                <div>
                    <div id="lineChart"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row" style="display:none">
    <div class="col-lg-12">
        <div class="ibox ">
            <div class="ibox-title">
                <h5>Multiple Axes Line Chart Example </h5>
            </div>
            <div class="ibox-content">
                <div class="flot-chart">
                    <div class="flot-chart-content" id="ClaimCost_chartmultiline"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="ibox ">
            <div class="ibox-title">
                <h5># of Claims</h5>
            </div>
            <div class="ibox-content">
                <div id="ClaimCount_apexChart"></div>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="ibox ">
            <div class="ibox-title">
                <h5>Cost  of Claim </h5>
            </div>
            <div class="ibox-content">
                <div id="ClaimCost_apexChart"></div>
            </div>
        </div>
    </div>
</div>