Funeral.Web/Areas/Admin/Models/ViewModel/PrintViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Funeral.Web.Areas.Admin.Models.ViewModel
{
    public class PrintViewModel
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public string PolicyNumber { get; set; }
        public string DatePaid { get; set; }
        public string AmountPaid { get; set; }
        public string PaidBy { get; set; }
        public string ReceivedBy { get; set; }
        public string MonthPaid { get; set; }
        public string ParlourName { get; set; }
        public string TimePrinted { get; set; }
        public string Underwriter { get; set; }
        public string BusinessAddressLine1 { get; set; }
        public string BusinessAddressLine2 { get; set; }
        public string BusinessAddressLine3 { get; set; }
        public string BusinessPostalCode { get; set; }
        public string FSBNumber { get; set; }
        public string telephoneNumber { get; set; }

        public string SurName { get; set; }
        public string FullName { get; set; }
        public string Barcode { get;set; }
    }
}

Funeral.Web/Areas/Admin/Controllers/TombstoneController.cs
using Funeral.BAL;
using Funeral.Model;
using Funeral.Web.App_Start;
using Funeral.Web.Areas.Admin.Models.ViewModel;
using Funeral.Web.Common;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace Funeral.Web.Areas.Admin.Controllers
{
    public class TombstoneController : BaseAdminController
    {
        public TombstoneController() : base(11)
        {
            this.dbPageId = 11;
        }

        /// <summary>
        /// Index method to Display List and add page
        /// </summary>
        /// <returns></returns>
        [PageRightsAttribute(CurrentPageId = 11, Right = new isPageRight[] { isPageRight.HasAccess })]
        public ActionResult Index()
        {
            //ViewBag.HasAccess = HasAccess;
            return View("Index");
        }

        /// <summary>
        /// this will display the count of list to display
        /// </summary>
        /// <returns></returns>
        public List<KeyValue> GetEntriesCount()
        {
            List<KeyValue> keyValues = new List<KeyValue>();
            keyValues.Add(new KeyValue { Key = "10", Value = "10" });
            keyValues.Add(new KeyValue { Key = "20", Value = "20" });
            keyValues.Add(new KeyValue { Key = "25", Value = "25" });
            keyValues.Add(new KeyValue { Key = "50", Value = "50" });
            keyValues.Add(new KeyValue { Key = "100", Value = "100" });
            keyValues.Add(new KeyValue { Key = "200", Value = "200" });
            keyValues.Add(new KeyValue { Key = "250", Value = "250" });
            keyValues.Add(new KeyValue { Key = "500", Value = "500" });
            return keyValues;
        }

        /// <summary>
        /// list method to display list of quatation
        /// </summary>
        /// <returns></returns>
        [PageRightsAttribute(CurrentPageId = 11)]
        public PartialViewResult List()
        {
            //ViewBag.HasEditRight = HasEditRight;
            //ViewBag.HasDeleteRight = HasDeleteRight;

            Model.Search.BaseSearch search = new Model.Search.BaseSearch();
            search.PageNum = 1;
            search.PageSize = 10;
            search.SarchText = string.Empty;
            search.SortBy = "";
            search.SortOrder = "Asc";
            search.TotalRecord = 0;

            var searchResult = new SearchResult<Model.Search.BaseSearch, TombStoneModel>(search, new List<TombStoneModel>(), o => o.LastName.Contains(search.SarchText) || o.FirstName.Contains(search.SarchText) || o.IDNumber.Contains(search.SarchText));

            var pageCountEntries = GetEntriesCount();
            ViewBag.EntriesCount = pageCountEntries;

            return PartialView("~/Areas/Admin/Views/Tombstone/_TombstoneList.cshtml", search);
        }
        /// <summary>
        /// method to search data as per user input
        /// </summary>
        /// <param name="search"></param>
        /// <returns></returns>
        public ActionResult SearchData(Model.Search.BaseSearch search)
        {
            var searchResult = new SearchResult<Model.Search.BaseSearch, TombStoneModel>(search, new List<TombStoneModel>(), o => o.LastName.Contains(search.SarchText) || o.FirstName.Contains(search.SarchText) || o.IDNumber.Contains(search.SarchText));
            try
            {
                var tombStoneList = TombStoneBAL.SelectAllTombStoneByParlourId(ParlourId, search.PageSize, search.PageNum, "", search.SortBy, search.SortOrder);
                return Json(new SearchResult<Model.Search.BaseSearch, TombStoneModel>(search, tombStoneList, o => o.FirstName.Contains(search.SarchText) || o.LastName.Contains(search.SarchText) || o.IDNumber.Contains(search.SarchText)));
            }
            catch (Exception ex)
            {
                return Json(WebApiResult<Model.Search.BaseSearch, TombStoneModel>.Error(searchResult, ex));
            }
        }
        /// <summary>
        /// Add method to display page
        /// </summary>
        /// <param name="tombStoneModel"></param>
        /// <returns></returns>
        [PageRightsAttribute(CurrentPageId = 11, Right = new isPageRight[] { isPageRight.HasAdd})]
        public PartialViewResult Add(TombStoneModel tombStoneModel)
        {
            tombStoneModel.parlourid = ParlourId;
            ModelState.Clear();
            return PartialView("~/Areas/Admin/Views/Tombstone/_TombstoneAddEdit.cshtml", tombStoneModel);
        }
        /// <summary>
        /// Edit Method for Edit Tombstone 
        /// </summary>
        /// <param name="pkiTombstoneID"></param>
        /// <returns></returns>
        [PageRightsAttribute(CurrentPageId = 11, Right = new isPageRight[] { isPageRight.HasEdit})]
        public PartialViewResult Edit(int pkiTombstoneID)
        {
            //Index();
            var funeral = TombStoneBAL.SelectTombStoneByParlAndPki(pkiTombstoneID, ParlourId);
            if (funeral != null)
            {
                Session["TombStoneID"] = funeral.pkiTombstoneID;
            }
            return PartialView("~/Areas/Admin/Views/Tombstone/_TombstoneAddEdit.cshtml", funeral);
        }
        /// <summary>
        /// Save method for saving tombstone 
        /// </summary>
        /// <param name="tombStoneModel"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Save(TombStoneModel tombStoneModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var TombstoneData = TombStoneBAL.SaveTombStone(tombStoneModel);
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        /// <summary>
        /// Tombstone payment method get data by tombstone id
        /// </summary>
        /// <param name="pkiTombstoneID"></param>
        /// <returns></returns>
        public ActionResult TombstonePayment(int pkiTombstoneID)
        {
            try
            {
                TombStonePaymentVM objTombStonePaymentVM = new TombStonePaymentVM();
                objTombStonePaymentVM.TombStonePaymentList = TombStonesPaymentBAL.TombStonesPaymentSelectByTombstoneID(ParlourId, pkiTombstoneID);
                objTombStonePaymentVM.TombStoneServiceList = TombStoneBAL.SelectServiceByTombStoneID(pkiTombstoneID);
                objTombStonePaymentVM.objTombStoneModel = TombStoneBAL.SelectTombStoneByParlAndPki(pkiTombstoneID, ParlourId);
                objTombStonePaymentVM.TombStoneNumber = objTombStonePaymentVM.objTombStoneModel.pkiTombstoneID.ToString();
                objTombStonePaymentVM.ReceivedBy = User.Identity.Name;
                return View(objTombStonePaymentVM);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        /// <summary>
        /// Tombstone Service by tombstone id
        /// </summary>
        /// <param name="pkiTombstoneID"></param>
        /// <returns></returns>
        public ActionResult TombStoneServiceSelect(int pkiTombstoneID)
        {
            TombStoneServiceVM objTomstone = new TombStoneServiceVM();
            objTomstone.Currency = Currency;
            objTomstone.TaxSettings = TaxSettingBAL.GetAllTaxSettings().Select(f => new SelectListItem { Text = f.TaxText, Value = f.TaxValue.ToString() }).ToList();
            objTomstone.ApplicationSettings = ToolsSetingBAL.GetApplictionByParlourID(ParlourId);
            objTomstone.ServiceType = QuotationBAL.GetAllQuotationServices(ParlourId).Select(f => new SelectListItem { Text = f.ServiceName, Value = f.pkiServiceID.ToString() }).ToList();
            objTomstone.objTombStoneModel = TombStoneBAL.SelectTombStoneByParlAndPki(pkiTombstoneID, ParlourId);
            objTomstone.ServiceList = TombStoneBAL.SelectServiceByTombStoneID(pkiTombstoneID);
            objTomstone.GetAllPackage = TombstonePackageBAL.SelectAllPackage(ParlourId).Select(f => new SelectListItem { Text = f.PackageName, Value = f.pkiPackageID.ToString() }).ToList();
            objTomstone.ModelBankDetails = ToolsSetingBAL.GetBankingByID(ParlourId);
            objTomstone.ModelTermsAndCondition = ToolsSetingBAL.SelectApplicationTermsAndCondition(ParlourId);
            objTomstone.TombStonesPaymentModelList = TombStonesPaymentBAL.TombStonesPaymentSelectByTombstoneID(ParlourId, pkiTombstoneID);
            var dueDate = objTomstone.objTombStoneModel.CreatedDate;
            DateTime newDueDate = dueDate.AddHours(48);
            ViewBag.DueDate = newDueDate.ToString("dd/MMM/yyyy");
            ViewBag.CreatedDate = objTomstone.objTombStoneModel.CreatedDate.ToString("dd/MMM/yyyy");
            return View(objTomstone);
        }
        /// <summary>
        /// Save Tombstone service 
        /// </summary>
        /// <param name="tombStoneServicePackageVM"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SavePackageForTombStoneService(TombStoneServicePackageVM tombStoneServicePackageVM)
        {
            var modelList = TombstonePackageBAL.SelectPackageServiceByPackgeId(ParlourId, tombStoneServicePackageVM.pkiServiceID);
            TombStoneServiceSelectModel model = new TombStoneServiceSelectModel();
            if (modelList != null || modelList.Count > 0)
            {
                foreach (var item in modelList)
                {
                    model.fkiTombstoneID = tombStoneServicePackageVM.fkiTombstoneID;
                    model.fkiServiceID = tombStoneServicePackageVM.fkiServiceID;
                    model.Quantity = 1;
                    model.lastModified = DateTime.Now;
                    model.modifiedUser = UserName;
                    model.ServiceRate = tombStoneServicePackageVM.ServiceRate;

Funeral.Web/Areas/Admin/Views/Tombstone/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Scripts.Render("~/bundles/jquery")

<script src="~/Scripts/app/searchdatatable.js"></script>
<script src="~/Scripts/plugins/dateformat/DateFormat.js"></script>

<div class="row" id="TombstoneAddedit"></div>
<div class="row" id="TombstoneList"></div>
<style>
    .modal-backdrop {
        position: fixed;
        top: auto !important;
        right: 0;
        bottom: 0;
        left: 0;
        z-index: 1040;
        background-color: #000;
    }

    .modal {
        position: fixed;
        top: 60% !important;
        right: 0;
        bottom: 0;
        left: 0;
        z-index: 1050;
        display: none;
        overflow: auto;
        -webkit-overflow-scrolling: touch;
        outline: 0;
    }
</style>
<script>
    var TombstoneID = '@ViewBag.pkiTombstoneID';
    var hasRight = '@ViewBag.HasAccess';
    jQuery(function ($) {
        $(document).ready(function () {
            
                $.noConflict();
                LoadTombstoneList();
                LoadTombstoneAddEdit();
                DOMIDs.AddEdit = "TombstoneAddedit";
                DOMIDs.List = "TombstoneList";
        });
    });

    function LoadTombstoneList() {
        jQuery.ajax({
            url: '@Url.Action("List", "Tombstone", new {},Request.Url.Scheme)',
            type: "Get",
            contentType: "application/html; charset=utf-8",
            dataType: 'html'
        })
        .success(function (result) {
            jQuery("#" + DOMIDs.List).html(result);
        })
        .error(function (xhr, status) {
            alert(status);
        });
    }

    function LoadTombstoneAddEdit() {

        var model = {
            pkiTombstoneID: 0,
            IDNumber: '',
            Title: '',
            LastName: '',
            FirstName: '',
            PolicyNumber: '',
            Address1: '',
            Address2: '',
            Address3: '',
            Address4: '',
            Code: '',
            TelNumber: '',
            CellNumber: '',
            DeceasedLastName: '',
            DeceasedFirstName: '',
            DeceasedIDNumber: '',
            Deceased: '',
            CemeterOrCrematorium: '',
            GraveNo: '',
            Erect: '',
            TombStoneMessage: '',
            Notes: '',
            parlourid: '',
            ModifiedUser: '',
            ImageName: '',
            ImagePath: '',
            InvoiceNumber: '',
            InvoiceNumber2: '',
            DisCount: '',
            Tax: '',
            ContactPerson: '',
            ContactPersonNumber: '',
        };

        jQuery.ajax({
            url: '@Url.Action("Add", "Tombstone", new {},Request.Url.Scheme)',
            type: "Post",
            data: JSON.stringify(model),
            contentType: "application/html; charset=utf-8",
            dataType: 'html'
        })
        .success(function (result) {
            jQuery("#" + DOMIDs.AddEdit).html(result);
        })
        .error(function (xhr, status) {
            alert(status);
        });
    }

    function PaymentHistory(pkiTombstoneID) {
        jQuery("#ucPaymentHistory").modal({
            show: 'true'
        });
        $('#ucPaymentHistory').parent().position({ my: 'center', of: 'center', collison: 'fit' });
        data = {
            pkiTombstoneID: pkiTombstoneID
        }
        $.ajax({
            url: '@Url.Action("PaymentHistory", "Tombstone")',
            data: data,
            type: "Get",
        })
        .success(function (result) {
            if (result.TombStonePaymentList != null) {
                var test = "";
                for (var i = 0; i < result.TombStonePaymentList.length; i++) {
                    test += "<tr>";
                    var data = result.TombStonePaymentList[i].DatePaid;

                    var date = new Date(parseInt(data.replace('/Date(', '')));
                    date = dateFormat(date, dateFormat.masks.isoDate, true);
                    test += "<td class='visible-lg'>" + date.toString("dd-mm-yyyy") + "</td>";
                    test += "<td align='right'>" + result.TombStonePaymentList[i].AmountPaid + "</td>";
                    test += "<td class='visible-lg'>" + result.TombStonePaymentList[i].RecievedBy + "</td>";
                    test += "<td class='visible-lg'>" + result.TombStonePaymentList[i].Notes + "</td>";
                    test += "<td class='visible-lg'>&nbsp;<a id='ucPaymenthistory' title='Click here Print' target='_blank' href='" + '@Url.Action("PrintForm", "Tombstone")' + "'><i class='glyphicon glyphicon-print'></i></a></td>";
                    test += "</tr>";
                    $("#tbodyPaymentHistory").html(test);
                }

            } else {

            }
        })
        .error(function (xhr, status) {
            alert(status);
        })
    }



</script>

Funeral.Web/Areas/Admin/Views/Tombstone/TombstonePayment.cshtml
@model Funeral.Web.Areas.Admin.Models.ViewModel.TombStonePaymentVM
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>FuneralPayment</title>
</head>
<body>
    <div class="wrapper wrapper-content animated fadeInRight">

        <div class="row">
            <div class="col-lg-12">
                <div class="ibox ">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="ibox float-e-margins">
                                <div class="ibox-title">
                                    <h5>Payment Details</h5>
                                </div>
                                <div class="ibox-content">
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>Tombstone Number</label>
                                                @Html.TextBoxFor(m => m.TombStoneNumber, "", new { @maxlength = "255", @readonly = "readonly", @id = "txtFuneralId", @class = "form-control" })
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>Received By  </label>
                                                @Html.TextBoxFor(m => m.ReceivedBy, "", new { @maxlength = "255", @readonly = "readonly", @id = "txtReceivedBy", @class = "form-control" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>Total Amount</label>
                                                @Html.TextBoxFor(m => m.TotalAmount, "", new { @maxlength = "255", @id = "txtAmount", @class = "form-control" })
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>Method</label>
                                                <select name="ddlMethod" id="ddlMethod" class="form-control m-b">
                                                    <option value="0">Select</option>
                                                    <option value="1">Cash</option>
                                                    <option value="2">Easy Pay</option>
                                                    <option value="3">Debit Order</option>
                                                    <option value="4">Bank Depost</option>
                                                    <option value="5">EFT</option>
                                                    <option value="6">Other</option>

                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>Month Paid<em>*</em>  </label>
                                                <textarea name="txtMohthPaid" rows="2" cols="20" id="txtMohthPaid" class="form-control" type="text" style="margin: 0px -4.25px 0px 0px; width: 292px; height: 73px;"></textarea>
                                            </div>

                                            <div class="form-group">
                                                <a name="btnBack" href="@Url.Action("Index","Tombstone")"  value="Click here to go back" id="btnBack" class="btn btn-md btn-primary" style="width:95%;">Click here to go back</a>
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <button name="btnPay" value="Add Payment" id="btnPay" class="btn btn-md btn-primary" style="width:95%;">Add Payment</button>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="ibox ">
                                <div class="ibox-title">
                                    <h5>Invoice</h5>
                                    <br>
                                    <br>
                                    <div class="table-responsive">
                                        <div>
                                            <table class="table table-striped table-bordered table-hover" cellspacing="0" rules="all" border="1" id="MainContent_gvServiceList" style="width:100%;border-collapse:collapse;">
                                                <tbody>
                                                    <tr>
                                                        <th class="visible-lg" scope="col">Service Name</th>
                                                        <th class="visible-lg" scope="col">Desctiption</th>
                                                        <th class="visible-lg" scope="col">Rate</th>
                                                        <th class="visible-lg" scope="col">QTY</th>
                                                        <th class="visible-lg" scope="col">Amount</th>
                                                    </tr>

                                                    @if (Model.TombStoneServiceList.Count > 0)
                                                    {
                                                        foreach (var item in Model.TombStoneServiceList)
                                                        {
                                                            <tr>
                                                                <td class="visible-lg">@item.ServiceName</td>
                                                                <td class="visible-lg">@item.ServiceDesc</td>
                                                                <td class="visible-lg">@item.ServiceCost</td>
                                                                <td class="visible-lg">@item.Quantity</td>
                                                                <td class="visible-lg" align="right">R @item.Amount.ToString("0.00")</td>
                                                            </tr>
                                                        }
                                                    }
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="modal-header">
                <h4 class="modal-title">Payment history</h4>
            </div>

            <div class="col-lg-12">
                <div class="table-responsive">
                    <div>
                        <table class="table table-striped table-bordered table-hover" cellspacing="0" rules="all" border="1" id="MainContent_ucPaymenthistory_gvInvoices" style="width:100%;border-collapse:collapse;">
                            <tbody>
                                <tr>
                                    <th class="visible-lg" scope="col">Date paid</th>
                                    <th scope="col">Amount</th>
                                    <th class="visible-lg" scope="col">Recieved by</th>
                                    <th class="visible-lg" scope="col">Months Paid &amp; Notes</th>
                                    <th scope="col">Actions</th>
                                </tr>
                                @if (Model.TombStonePaymentList.Count > 0)
                                {
                                    foreach (var item in Model.TombStonePaymentList)
                                    {
                                        <tr>
                                            <td class="visible-lg">@item.DatePaid</td>
                                            <td align="left">@item.AmountPaid.ToString("0.00")</td>
                                            <td class="visible-lg">@item.RecievedBy</td>
                                            <td class="visible-lg">@item.Notes</td>
                                            <td>
                                                &nbsp;
                                                <a id="ucPaymenthistory" title="Click here Print " href="@Url.Action("PrintForm","Tombstone")"><i class="glyphicon glyphicon-print"></i></a>

                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>

    </div>



    <script>
        $(document).ready(function () {
            $("#txtAmount").val('');
            $("#txtAmount").val("0.00");
        })
        $("#btnPay").click(function () {
            var notes = $("#ddlMethod :selected").text() +" - "+ $("#txtMohthPaid").val()
            data = {
                TombstoneID: $("#txtFuneralId").val(),
                AmountPaid: $("#txtAmount").val(),
                RecievedBy: $("#txtReceivedBy").val(),
                Notes: notes
            }
            $.ajax({
                type: "post",
                url: '@Url.Action("TombStonePaymentAddPayment", "TombStone")',
                data: data,
                success: function (result) {
                    if (result == "Payment added successfully.") {
                        alert("Payment added successfully.");
                        location.reload();
                    }
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("Request: " + XMLHttpRequest.toString() + "\n\nStatus: " + textStatus + "\n\nError: " + errorThrown);
                }
            });
        })
    </script>
</body>
</html>