Funeral.Web/Areas/Admin/Controllers/ParlourController.cs
using System;
using System.Web.Mvc;

namespace Funeral.Web.Areas.Admin.Controllers
{
    public class ParlourController : BaseAdminController
    {
        // GET: Admin/Parlour
        [HttpPost]
        public void ChangeParlour(Guid parlourId)
        {
            if (!parlourId.Equals(Guid.Empty))
            {
                CurrentParlourId = parlourId;
            }
        }
    }
}

Funeral.Web/Areas/Admin/Controllers/SchemaPaymentController.cs
using Funeral.BAL;
using Funeral.Model;
using Funeral.Web.App_Start;
using Funeral.Web.Common;
using Microsoft.Reporting.WebForms;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Web.Mvc;

namespace Funeral.Web.Areas.Admin.Controllers
{
    public class SchemaPaymentController : BaseAdminController
    {
        // GET: Admin/SchemaPayment
        private readonly ISiteSettings _siteConfig = new SiteSettings();
        public ActionResult Index()
        {
            return View();
        }
        public List<KeyValue> GetEntriesCount()
        {
            List<KeyValue> keyValues = new List<KeyValue>();
            keyValues.Add(new KeyValue { Key = "10", Value = "10" });
            keyValues.Add(new KeyValue { Key = "20", Value = "20" });
            keyValues.Add(new KeyValue { Key = "25", Value = "25" });
            keyValues.Add(new KeyValue { Key = "50", Value = "50" });
            keyValues.Add(new KeyValue { Key = "100", Value = "100" });
            keyValues.Add(new KeyValue { Key = "200", Value = "200" });
            keyValues.Add(new KeyValue { Key = "250", Value = "250" });
            keyValues.Add(new KeyValue { Key = "500", Value = "500" });
            return keyValues;
        }
        public PartialViewResult SchemaList()
        {
            BindCompanyList("Search");
            ViewBag.HasEditRight = HasEditRight;
            ViewBag.HasDeleteRight = HasDeleteRight;
            Model.Search.PaymentSearchNew search = new Model.Search.PaymentSearchNew();
            search.PageNum = 1;
            search.PageSize = 10;
            search.SarchText = string.Empty;
            search.SortBy = "";
            search.SortOrder = "Asc";
            search.TotalRecord = 0;
            var searchResult = new SearchResult<Model.Search.BaseSearch, SocietyModel>(search, new List<SocietyModel>(), o => o.SocietyName.Contains(search.SarchText));

            var pageCountEntries = GetEntriesCount();
            ViewBag.EntriesCount = pageCountEntries;

            return PartialView("~/Areas/Admin/Views/SchemaPayment/_SchemaList.cshtml", search);
        }
        public ActionResult GroupSearchData(Model.Search.PaymentSearchNew search)
        {
            var searchResult = new SearchResult<Model.Search.BaseSearch, SocietyModel>(search, new List<SocietyModel>(), o => o.SocietyName.Contains(search.SarchText));

            try
            {
                var SocietyList = ToolsSetingBAL.GetAllSocietyes_PaymentList(CurrentParlourId);
                SocietyList = search.StatusId != Guid.Empty ? SocietyList.Where(x => x.parlourid.Equals(search.StatusId)).ToList() : SocietyList; // StatusID => CompanyId
                return Json(new SearchResult<Model.Search.BaseSearch, GroupPaymentList>(search, SocietyList, o => o.GroupName.Contains(search.SarchText)));
            }
            catch (Exception ex)
            {
                return Json(WebApiResult<Model.Search.BaseSearch, SocietyModel>.Error(searchResult, ex));
            }
        }
        #region Open Regenrated Billing PopUp
        [HttpGet]
        public ActionResult RegenerateBillingPartial(Guid ParlourId, string ReferenceNumber)
        {

            RegenerateBillingModal modal = new RegenerateBillingModal();
            modal.parlourId = ParlourId;
            modal.PremiumDueDate = DateTime.Now;
            modal.ReferenceNumber = ReferenceNumber;
            return PartialView("_RegenerateBillingModal", modal);
        }
        [HttpPost]
        public ActionResult SaveRegenerateBilling(RegenerateBillingModal modal)
        {
            if (ModelState.IsValid)
            {
                int value = MemberPaymentBAL.RecreateBillingMemberPayments(modal);
                if (value > 0)
                    TempData["message"] = ShowMessage(MessageType.Success, "Billing Regenerate Successfully");
                else
                    TempData["message"] = ShowMessage(MessageType.Danger, "Billing could not regenerate");
            }
            else
            {
                TempData["message"] = ShowMessage(MessageType.Danger, "Billing could not regenerate");
            }
            return Redirect(Request.UrlReferrer.ToString());
        }
        #endregion
        [HttpGet]
        public ActionResult DownloadReportPartial(Guid ParlourId, string ReferenceNumber)
        {
            string ExportTypeExtensions = "xls";
            string ReportName = "ARL_Scheme_Billing Report";
            Warning[] warnings;
            string[] streamids;
            string mimeType;
            string encoding;
            string extension;
            string filename;

            ReportViewer rpw = new ReportViewer();
            rpw.ProcessingMode = ProcessingMode.Remote;
            IReportServerCredentials irsc = new MyReportServerCredentials();
            rpw.ServerReport.ReportServerCredentials = irsc;


            rpw.ProcessingMode = ProcessingMode.Remote;
            rpw.ServerReport.ReportServerUrl = new Uri(_siteConfig.SSRSUrl);
            rpw.ServerReport.ReportPath = "/" + _siteConfig.SSRSFolderName + "/" + ReportName;
            ReportParameterCollection reportParameters = new ReportParameterCollection();
            reportParameters.Add(new ReportParameter("DateFrom", DateTime.Now.ToString("yyyy/MM/dd")));
            reportParameters.Add(new ReportParameter("DateTo", DateTime.Now.ToString("yyyy/MM/dd")));
            reportParameters.Add(new ReportParameter("Parlourid", ParlourId.ToString()));
            reportParameters.Add(new ReportParameter("RefNo", ReferenceNumber));
            rpw.ServerReport.SetParameters(reportParameters);
            byte[] bytes = rpw.ServerReport.Render("Excel", null, out mimeType, out encoding, out extension, out streamids, out warnings);
            filename = string.Format("{0}.{1}", ReportName, ExportTypeExtensions);

            Response.ClearHeaders();
            Response.Clear();
            Response.AddHeader("Content-Disposition", "attachment;filename=" + filename);
            Response.ContentType = mimeType;
            Response.BinaryWrite(bytes);
            Response.Flush();
            Response.End();
            return File(bytes, System.Net.Mime.MediaTypeNames.Application.Octet, filename);
        }
        [HttpGet]
        public ActionResult SendEmailReportPartial(Guid ParlourId, string ReferenceNumber)
        {
            ReportParameters modal = new ReportParameters();
            modal.parlourId = ParlourId;
            modal.fromDate = DateTime.Now;
            modal.toDate = DateTime.Now;
            modal.ReferenceNumber = ReferenceNumber;
            return PartialView("_ReportEmailSendModal", modal);
        }
        [HttpPost]
        public ActionResult SendEmailReport(ReportParameters modal)
        {
            if (ModelState.IsValid)
            {
                string ExportTypeExtensions = "xls";
                modal.ReportName = "ARL_Scheme_Billing Report";
                Warning[] warnings;
                string[] streamids;
                string mimeType;
                string encoding;
                string extension;
                string filename;

                ReportViewer rpw = new ReportViewer();
                rpw.ProcessingMode = ProcessingMode.Remote;
                IReportServerCredentials irsc = new MyReportServerCredentials();
                rpw.ServerReport.ReportServerCredentials = irsc;


                rpw.ProcessingMode = ProcessingMode.Remote;
                rpw.ServerReport.ReportServerUrl = new Uri(_siteConfig.SSRSUrl);
                rpw.ServerReport.ReportPath = "/" + _siteConfig.SSRSFolderName + "/" + modal.ReportName;
                ReportParameterCollection reportParameters = new ReportParameterCollection();
                reportParameters.Add(new ReportParameter("DateFrom", modal.fromDate.ToString("yyyy/MM/dd")));
                reportParameters.Add(new ReportParameter("DateTo", modal.toDate.ToString("yyyy/MM/dd")));
                reportParameters.Add(new ReportParameter("Parlourid", modal.parlourId.ToString()));
                reportParameters.Add(new ReportParameter("RefNo", modal.ReferenceNumber.ToString()));
                rpw.ServerReport.SetParameters(reportParameters);
                byte[] bytes = rpw.ServerReport.Render("Excel", null, out mimeType, out encoding, out extension, out streamids, out warnings);
                filename = string.Format("{0}.{1}", modal.ReportName, ExportTypeExtensions);

                if (!string.IsNullOrEmpty(modal.Email))
                {
                    MemoryStream s = new MemoryStream(bytes);
                    s.Seek(0, SeekOrigin.Begin);
                    Attachment a = new Attachment(s, filename);
                    MailMessage message = new MailMessage(ConfigurationManager.AppSettings["ReportEmailSenderId"].ToString().Trim(), modal.Email.Trim(), modal.ReportName, "");
                    message.Attachments.Add(a);
                    SmtpClient client = new SmtpClient();
                    client.Send(message);
                    TempData["message"] = ShowMessage(MessageType.Success, "Email Sent Successfully");
                }
                else
                {
                    TempData["message"] = ShowMessage(MessageType.Success, "Please Enter Email");
                }
            }

            return Redirect(Request.UrlReferrer.ToString());
        }

        [HttpGet]
        public ActionResult DownloadReconBillingReportPartial(Guid ParlourId, string ReferenceNumber)
        {
            string ExportTypeExtensions = "xls";
            string ReportName = "ARL_Scheme_Billing Report"; //ARL_Scheme_Billing Recon Report
             Warning[] warnings;
            string[] streamids;
            string mimeType;
            string encoding;
            string extension;
            string filename;

Funeral.Web/Areas/Admin/Views/SchemaPayment/Index.cshtml
@model Funeral.Model.MembersPaymentViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Scripts.Render("~/bundles/jquery")

<script src="~/Scripts/app/searchdatatable.js"></script>
<div class="row" id="MembersPaymentList"></div>
<script>
    var PkiMemberIDId = '@ViewBag.MemberID';
     var hasRight = '@ViewBag.HasAccess';
    jQuery(function ($) {
        jQuery(document).ready(function () {
            $.noConflict();
            LoadSocietyList();
                DOMIDs.List = "MembersPaymentList";
        });
    })

    function LoadSocietyList() {

        jQuery.ajax({
            url: '@Url.Action("SchemaList", "SchemaPayment", new {},Request.Url.Scheme)',
            type: "Get",
            contentType: "application/html; charset=utf-8",
            dataType: 'html'
        })
			.success(function (result) {
            jQuery("#" + DOMIDs.List).html(result);
        })
        .error(function (xhr, status) {
            alert(status);
        });
    }
</script>

Funeral.Web/Areas/Admin/Views/SchemaPayment/_ReconReportModal.cshtml
@model Funeral.Model.ReportParameters
@{
    using (Html.BeginForm("ReconReportDownload", "SchemaPayment", FormMethod.Post))
    {
        @Html.HiddenFor(x => x.parlourId)
        @Html.HiddenFor(x => x.ReferenceNumber)
        <div id="RegenerateBillingModalPopUp" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="DoCModalLabel">Download Report</h4>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <div class="col-sm-6">
                                        <label>From Date</label>
                                        @Html.TextBoxFor(x => x.fromDate, "{0:dd MMM yyyy}", new { @id = "txtToDate", @class = "form-control DatepickerSelection", @autocomplete = false,@required=true })
                                    </div>
                                    <div class="col-sm-6">
                                        <label>To Date</label>
                                        @Html.TextBoxFor(x => x.toDate, "{0:dd MMM yyyy}", new { @id = "txtFromDate", @class = "form-control DatepickerSelection", @autocomplete = false,@required=true })
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary" value="Submit">Download</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    }
}

Funeral.Web/Areas/Admin/Views/SchemaPayment/_RegenerateBillingModal.cshtml
@model Funeral.Model.RegenerateBillingModal
@{
    using (Html.BeginForm("SaveRegenerateBilling", "SchemaPayment", FormMethod.Post))
    {
        @Html.HiddenFor(x => x.parlourId)
        <div id="RegenerateBillingModalPopUp" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="DoCModalLabel">Regenerate Billing</h4>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <div class="col-sm-6">
                                        <label>Premium due date</label>
                                        @Html.TextBoxFor(x => x.PremiumDueDate, "{0:dd MMM yyyy}", new { @id = "txtPremiumDueDate", @class = "form-control DatepickerSelection", @autocomplete = false ,@required=true})
                                    </div>
                                    <div class="col-sm-6">
                                        <label>Reference Number</label>
                                        @Html.TextBoxFor(x => x.ReferenceNumber, new { @type = "text", @id = "txtRefNumber", @class = "form-control",@readonly=true,@required=true })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary" value="Submit">Submit</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    }
}

Funeral.Web/Areas/Admin/Views/SchemaPayment/_ReportParametersModal.cshtml
@model Funeral.Model.ReportParameters
@{
    using (Html.BeginForm("DownloadReport", "SchemaPayment", FormMethod.Post))
    {
        @Html.HiddenFor(x => x.parlourId)
        @Html.HiddenFor(x => x.ReferenceNumber)
        <div id="RegenerateBillingModalPopUp" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="DoCModalLabel">Download Report</h4>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <div class="col-sm-6">
                                        <label>From Date</label>
                                        @Html.TextBoxFor(x => x.fromDate, "{0:dd MMM yyyy}", new { @id = "txtToDate", @class = "form-control DatepickerSelection", @autocomplete = false, @required = true })
                                    </div>
                                    <div class="col-sm-6">
                                        <label>To Date</label>
                                        @Html.TextBoxFor(x => x.toDate, "{0:dd MMM yyyy}", new { @id = "txtFromDate", @class = "form-control DatepickerSelection", @autocomplete = false, @required = true })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary" value="Submit">Download</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    }
}

Funeral.Web/Areas/Admin/Views/SchemaPayment/_SchemaList.cshtml
@model Funeral.Model.Search.PaymentSearchNew
@Styles.Render("~/Content/datatablecss")


<script src="~/Scripts/plugins/dateformat/DateFormat.js"></script>


@using (Html.BeginForm())
{
    <div class="dataTables_wrapper" id="tblSocietySetupSearch_wrapper">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <h5>Group List</h5>
                </div>
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-lg-3" id="dvAdministrator">
                            <div class="form-group">
                                <label>Show Entries:</label>
                                @Html.DropDownListFor(m => m.PageSize, new SelectList(ViewBag.EntriesCount, "Value", "Key"), new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label>Scheme: </label>
                                @Html.DropDownList("ddlSelectCompany", new SelectList(ViewBag.Companies, "parlourid", "ApplicationName"),"Choose Scheme" ,new { @id = "ddlSelectCompany", @class = "form-control" })
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                @Html.Label("Search Scheme:", new { @class = "control-label" })
                                <div class="input-group">
                                    @Html.TextBoxFor(m => m.SarchText, null, new { @class = "form-control", @maxlength = "50", placeholder = "Search by keyword" })
                                    <span class="input-group-btn">
                                        <input type="button" id="btnSearch" value="Search" class="btn btn-w-m btn-primary" />
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-9">
                            <asp:Label ID="lblRecords" runat="server" Text=""></asp:Label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12 ">
                            <div class="table-responsive">s
                                @Html.EditorFor(model => model.PageNum, new { htmlAttributes = new { @class = "hidden", id = "PageNum1" } })
                                @Html.EditorFor(model => model.PageSize, new { htmlAttributes = new { @class = "hidden", id = "PageSize1" } })
                                @Html.Hidden("ItemId")
                                <table id="societySetupDataTable" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>Group Name</th>
                                            <th>Premium</th>
                                            <th>Balance</th>
                                            @*<th>Duplicate Ids with Covers > 100k</th>
                                            <th>Amount At Risk</th>*@
                                            <th>Total Risk Covered</th>
                                            <th>Billing Month</th>
                                            <th>Reference Number</th>
                                            <th>Regenerate</th>
                                            <th>Recon</th>
                                            <th>Action &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</th>
                                        </tr>
                                    </thead>
                                    <tbody></tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $(document).ready(function () {


            ConfigureDatatable();
            InitDataTable();
            $('#PageSize').change(function () {
                InitModel();
                tableConfigs.table.DataTable().page.len(model1.PageSize).draw();
            });
            $("#btnSearch").click(function () {
                InitModel();
                tableConfigs.table.fnDraw();
            });
            $('#ddlSelectCompany').change(function () {
                jQuery.ajax({
                    url: '@Url.Action("ChangeParlour", "Parlour", null, Request.Url.Scheme)',
                    data: { parlourid: $('#ddlSelectCompany').val() },
                    type: "post",
                    cache: false,
                    success: function (result) {

                    }
                })
            });
        });

        function ConfigureDatatable() {
            var statusId = @Html.Raw(Json.Encode(@Model.StatusId));
            var sortOrder = @Html.Raw(Json.Encode(@Model.SortOrder));
            var sortBy =@Html.Raw(Json.Encode(@Model.SortBy));
            var totalRecord =@Html.Raw(Json.Encode(@Model.TotalRecord));
            var pageNum =@Html.Raw(Json.Encode(@Model.PageNum));
            var pageSize =@Html.Raw(Json.Encode(@Model.PageSize));
            var searchText =@Html.Raw(Json.Encode(@Model.SarchText));

			DOMIDs.Datatable = "societySetupDataTable";
            tableConfigs.SearchUrls = '@Url.Action("GroupSearchData", "SchemaPayment", new { }, Request.Url.Scheme)';
			setsearchmodel(statusId, sortOrder, sortBy, totalRecord, pageNum, pageSize, searchText);

            columnsArray =
                [{ "data": "GroupName", "name": "Group Name", "autoWidth": true },
                { "data": "Premium", "name": "Premium", "autoWidth": true },
                { "data": "Balance", "name": "Balance", "autoWidth": true },
                //{ "data": "DuplicateIDsWithCovers100K", "name": "DuplicateIDsWithCovers100K", "autoWidth": true },
                //{ "data": "AmountAtRisk", "name": "Amount At Risk", "autoWidth": true },
                { "data": "TotalRiskCovered", "name": "Total Risk Covered", "autoWidth": true },
                {
                    "data": "BillingMonth", "name": "Inception Date", "autoWidth": true,
                    "render": function (data) {
                        var date = new Date(parseInt(data.replace('/Date(', '')));
                        return dateFormat(date, dateFormat.masks.PerfectDate, true);
                    }
                },
                { "data": "ReferenceNumber", "name": "Reference Number", "autoWidth": true },
                {
                    "render": function (data, type, full, meta) {
                        var hasEditRights = '@ViewBag.HasEditRight' == "True" ? true : false;
                        var hasDeleteRights = '@ViewBag.HasDeleteRight' == "True" ? true : false;

                        var dom = "<div class='row'>";
                        var RegenerateBill = '<div class="col-sm-12"><a class="btn btn-primary btn-sm" placeholder="Regenerate Billing Schedule" onclick="OpenRegenerateBillingPopUp(\'' + full.parlourid + '\',\'' + full.ReferenceNumber + '\')"><i class="fa fa-file-code-o"></i> Regenerate Billing</a></div>';
                        dom = dom + RegenerateBill;

                        dom = dom + "</div>";
                        return dom;
                    }
                },
                {
                    "render": function (data, type, full, meta) {
                        var hasEditRights = '@ViewBag.HasEditRight' == "True" ? true : false;
                        var hasDeleteRights = '@ViewBag.HasDeleteRight' == "True" ? true : false;

                        var dom = "<div class='row'>";
                        var RegenerateBill = '<div class="col-sm-12"><a class="btn btn-primary btn-sm" placeholder="Regenerate Billing Schedule" onclick="DownloadReconReportPopUp(\'' + full.parlourid + '\',\'' + full.ReferenceNumber + '\')"><i class="fa fa-envelope"></i> Recon Billing</a></div>';
                        dom = dom + RegenerateBill;

                        dom = dom + "</div>";
                        return dom;
                    }
                },

                {
                    "render": function (data, type, full, meta) {
                        var hasEditRights = '@ViewBag.HasEditRight' == "True" ? true : false;
                        var hasDeleteRights = '@ViewBag.HasDeleteRight' == "True" ? true : false;

                        var dom = "<div class='row'>";
                        var SendMail = '<div class="col-sm-3"><a class="btn btn-primary btn-sm" placeholder="Send Email" onclick="SendReportEmail(\'' + full.parlourid + '\',\'' + full.ReferenceNumber + '\')"><i class="fa fa-envelope"></i></a></div>';
                        dom = dom + SendMail;

                        var Download = '<div class="col-sm-3"><a class="btn btn-primary btn-sm" placeholder="Download" onclick="DownloadReport(\'' + full.parlourid + '\',\'' + full.ReferenceNumber + '\')"><i class="fa fa-download"></i></a></div>';
                        dom = dom + Download;

                        //var Refresh = '<div class="col-sm-3"><a class="btn btn-primary btn-sm" placeholder="Refresh" onclick="RefreshBilling(\'' + full.parlourid + '\',\'' + full.ReferenceNumber + '\')"><i class="fa fa-refresh"></i></a></div>';
                        //dom = dom + Refresh;



                        dom = dom + "</div>";
                        return dom;
                    }
                }];
        }
        function InitModel() {
            model1.PageNum = 1;
            model1.PageSize = jQuery('#PageSize').val();
            model1.SarchText = jQuery("#SarchText").val();
            model1.StatusId = jQuery("#ddlSelectCompany").val();
            jQuery("#PageNum1").val(model1.PageNum);
        }
        function OpenRegenerateBillingPopUp(GetParlourId, referenceNumber) {
            var GetUrl = "@Url.Action("RegenerateBillingPartial","SchemaPayment",new {ParlourId="GetParlourId",ReferenceNumber="getreferenceNumber"})".replace("GetParlourId", GetParlourId).replace("getreferenceNumber", referenceNumber).replace("amp;","");
            jQuery.ajax({
                url: GetUrl,
                type: 'GET',
                cache: false,
            }).done(function (result) {

                jQuery('#LoadPartialView_ManageClaims').empty().html(result);
                jQuery("#RegenerateBillingModalPopUp").modal("show");

                jQuery('.modal-backdrop').removeClass("modal-backdrop");
                 $(".DatepickerSelection").datepicker({
                    format: 'dd M yyyy',
                    setDate: new Date(),
                    autoclose: true,
                    onSelect: function (dateText) { $(this).change(); }
                }).on("change", function () { });
            });
        }
        function DownloadReport(GetParlourId, referenceNumber) {
            var GetUrl = "@Url.Action("DownloadReportPartial","SchemaPayment",new {ParlourId="GetParlourId",ReferenceNumber="getreferenceNumber"})".replace("GetParlourId", GetParlourId).replace("getreferenceNumber", referenceNumber).replace("amp;","");;
            jQuery.ajax({
                url: GetUrl,
                contentType: 'application/json; charset=utf-8',
                datatype: 'json',
                type: 'GET',
                cache: false,
            }).done(function (result) {
                window.location = GetUrl;
            });
        }
        function SendReportEmail(GetParlourId, referenceNumber) {
            var GetUrl = "@Url.Action("SendEmailReportPartial","SchemaPayment",new {ParlourId="GetParlourId",ReferenceNumber="getreferenceNumber"})".replace("GetParlourId", GetParlourId).replace("getreferenceNumber", referenceNumber).replace("amp;","");;
            jQuery.ajax({
                url: GetUrl,
                type: 'GET',
                cache: false,
            }).done(function (result) {
                jQuery('#LoadPartialView_ManageClaims').empty().html(result);
                jQuery("#RegenerateBillingModalPopUp").modal("show");
                jQuery('.modal-backdrop').removeClass("modal-backdrop");
                $(".DatepickerSelection").datepicker({
                    format: 'dd M yyyy',
                    setDate: new Date(),
                    autoclose: true,
                    onSelect: function (dateText) { $(this).change(); }
                }).on("change", function () { });
            });
        }
         function DownloadReconReportPopUp(GetParlourId, referenceNumber) {
            var GetUrl = "@Url.Action("DownloadReconBillingReportPartial","SchemaPayment",new {ParlourId="GetParlourId",ReferenceNumber="getreferenceNumber"})".replace("GetParlourId", GetParlourId).replace("getreferenceNumber", referenceNumber).replace("amp;","");;
            jQuery.ajax({
                url: GetUrl,
                contentType: 'application/json; charset=utf-8',
                datatype: 'json',
                type: 'GET',
            }).done(function (result) {
               window.location = GetUrl;
            });
        }
    </script>
}